# Get rid of abbreviations

# This first list is for titles that have special characters and cannot be wrapped with the '\\b'
list_one <- c("SPEC. SVCS." = "SPECIAL SERVICES", "SPEC.COORD." = "SPECIFICATION COORDINATOR")
pattern_one <- str_c(names(list_one), collapse = "|")
abbrev2long <- function(abbr) {
    list_one[abbr]
}

current_titles$TitleLong <- str_replace_all(current_titles$TitleLong,
                                            pattern = pattern_one,
                                            replacement = abbrev2long)

# This second list is for terms that can be wrapped with '\\b'.

abbrev_list <- c("ASST" = "ASSISTANT" , "CHF" = "CHIEF", "DIV" = "DIVISION", "CNTR" = "CENTER",
                 "DIR" = "DIRECTOR", "EXEC" = "EXECUTIVE", "HD" = "HEAD", "HLTH SERVS" = "HEALTH SERVICES",
                 "HLTH" = "HEALTH", "MAINT" = "MAINTENANCE", "MGR" = "MANAGER", 
                 "MGMT" = "MANAGEMENT", "MGT" = "MANAGEMENT", "OPER" = "OPERATIONS", "PGMS" = "PROGRAMS", 
                 "PROG" = "PROGRAM", "PHYS" = "PHYSICIAN", "REG-REC/CO CLK" = "REGISTRAR-RECORDER/COUNTY CLERK", 
                 "SERVS" = "SERVICES", "SPEC" = "SPECIALIST", "SUPVG" = "SUPERVISING", "SVCS" = "SERVICES", 
                 "SVS" = "SERVICES", "DEP" = "DEPUTY", "REGISTRAR-REC/CO CLK" = "REGISTRAR-RECORDER/COUNTY CLERK",
                 "REG-REC/CO CLERK" = "REGISTRAR-RECORDER/COUNTY CLERK",
                 "REG-REC/CO CLK" = "REGISTRAR-RECORDER/COUNTY CLERK", "DEPTL" = "DEPARTMENTAL",
                 "REGISTRAR-RECORDER/CO CLK" = "REGISTRAR-RECORDER/COUNTY CLERK", "OPNS" = "OPERATIONS", "EMER" = "EMERGENCY",
                 "TTC" = "TREASURER AND TAX COLLECTOR", "INT MED" = "INTERNAL MED",
                 "INT DIAGNOSTIC" = "INT DIAGNOSITC", "RESEARCH TR" = "RESEARCH TRAINEE",
                 "MED" = "MEDICAL", "CTR" = "CENTER", "PHARM" = "PHARMACY", "OFC" = "OFFICE OF",
                 "PGM" = "PROGRAM", "ALCHL" = "ALCOHOL", "SUPVR" = "SUPERVISOR", "DEPY" = "DEPUTY", "TREAT" = "TREATMENT",
                 "DPY" = "DEPUTY", "OFCR" = "OFFICER", "OFFCR" = "OFFICER", "PROB" = "PROBATION", "WKR" = "WORKER",
                 "BLDG" = "BUILDING", "ENGRG" = "ENGINEERING", "ENGR" = "ENGINEER", "ASSOC" = "ASSOCIATE", 
                 "SVC" = "SERVICES", "MUS. O ART" = "MUSEUM OF ART", "MUS. OF ART" = "MUSEUM OF ART", 
                 "DPTY" = "DEPUTY", "SYS" = "SYSTEMS", "SR" = "SENIOR", "AST" = "ASSISTANT", "HOSP" = "HOSPITAL",
                 "CONSULT" = "CONSULTING", "EQUIP" = "EQUIPMENT", "FIGHTG" = "FIGHTING", "EQPT" = "EQUIPMENT",
                 "CONSTRUCT" = "CONSTRUCTION", "ADMR" = "ADMINISTRATOR", "COMP" = "COMPREHENSIVE",
                 "AMB" = "AMBULATORY", "ASSISTANT ADMN" = "ASSISTANT ADMINISTRATOR", "PRIN" = "PRINCIPAL",
                 "PRINCIPAL ADMN" = "PRINCIPAL ADMINISTRATOR", "ASSISTANT PROGRAM ADMN" = "ASSISTANT PROGRAM ADMINISTRATOR",
                 "ADMN SERVICES" = "ADMINISTRATIVE SERVICES", "AGRI COMM/WTS & MEAS" = "AGRICULTURAL COMMISSIONER/WEIGHTS AND MEASURES",
                 "PULMONARY PHYS TECH SUPV" = "PULMONARY PHYSIOLOGY TECHNICIAN SUPERVISOR", "ASST ADMN" = "ASSISTANT ADMINISTRATOR",
                 "INFORMATION TECHNOLOGY TECH SUPPORT SUPERVISOR" = "INFORMATION TECHNOLOGY TECHNICAL SUPPORT SUPERVISOR",
                 "PAT FINANCIAL SERVS CONTROL SUPV" = "PATIENT FINANCIAL SERVICES CONTROL SUPERVISOR",
                 "SUPV APPEALS" = "SUPERVISING APPEALS", "BD OF SUPVRS" = "BOARD OF SUPERVISORS", 
                 "BD OF SUPV" = "BOARD OF SUPERVISORS", "ENGINEER APP" = "ENGINEER APPRENTICE", "OFFR" = "OFFICER",
                 "BRD OF SUPVRS" = "BOARD OF SUPERVISORS", "BD OF SUP" = "BOARD OF SUPERVISORS",
                 "BOARD OF SUPVRS" = "BOARD OF SUPERVISORS", "PSS" = "PUBLIC SOCIAL SERVICES", 
                 "ELECTRONIC COMMUNIC TECH WKG SUPVRR" = "ELECTRONICS COMMUNICATIONS TECHNICIAN WORKING SUPERVISOR",
                 "SUPV CHILDREN'S" = "SUPERVISING CHILDREN'S", "PERSONNEL TECH" = "PERSONNEL TECHNICIAN",
                 "RECS" = "RECORDS", "MH" = "MENTAL HEALTH", "EMPL" = "EMPLOYEE",
                 "REP" = "REPRESENTATIVE", "CAPTAIN,DA" = "CAPTAIN, DISTRICT ATTORNEY", "WKG" = "WORKING",
                 "INFORMATION TECHNOLOGY TECH SUPPORT SUPERVISOR" = "INFORMATION TECHNOLOGY TECHNICAL SUPPORT SUPERVISOR",
                 "PUB DEFENDER" = "PUBLIC DEFENDER", "ADMIN DEPUTY" = "ADMINISTRATIVE DEPUTY", "ADMIN & FACILITIES" = "ADMINISTRATIVE & FACILITIES",
                 "ADMIN SYSTEMS" = "ADMINISTRATIVE SYSTEMS", "ADMIN," = "ADMINISTRATOR,", 
                 "ADMIN, CONTRACT" = "ADMINISTRATOR, CONTRACT", "ADMIN SERVICES" = "ADMINISTRATIVE SERVIES",
                 "CHIEF ADMIN" = "CHIEF ADMINISTRATIVE", "DEVELOPMENT ADMIN" = "DEVELOPMENT ADMINISTRATOR", 
                 "HUMAN RESOURCES ADMIN" = "HUMAN RESOURCES ADMINISTRATOR", "ADMIN SUPPORT" = "ADMINISTRATIVE SUPPORT",
                 "IT"="INFORMATION TECHNOLOGY", "MEDICAL SERVICE COORDINATOR,CCS" = "MEDICAL SERVICE COORDINATOR, CALIFORNIA CHILDREN SERVICES",
                 "CHF,ASSESS APPEALS BDS,BD OF SUPVRS" = "CHIEF, ASSESSMENT APPEALS BOARDS, BOARD OF SUPERVISORS",
                 "PHYSICIAN SPECIALIST, MF" = "MEGAFLEX", "PROC SVS" = "PROCESSING SERVICES", "CRD" = "COORDINATOR",
                 "COORD" = "COORDINATOR", "CFS" = "CHILDREN AND FAMILY SERVICES", "TESTING TECH" = "TESTING TECHNICIAN",
                 "SECTION MANAGER, INFO. TECH., SYSTEMS PROG., ISD" = "SECTION MANAGER, INFORMATION TECHNOLOGY, SYSTEMS PROGRAM, ISD",
                 "PARKS & REC" = "PARKS & RECREATION", "MKTG" = "MARKETING", "REPR" = "REPRESENTATIVE",
                 "UNCLASS" = "UNCLASSIFIED", "FIN SVS" = "FINANCIAL SERVICES", "OPR" = "OPERATOR", "A/C" = "AUDITOR/CONTROLLER",
                 "AUTO FINGERPRINT IDENTIFICATION SYST OPS SUPVR" = "AUTOMATED FINGERPRINT IDENTIFICATION SYSTEM OPERATIONS SUPERVISOR",
                 "GRNDS" = "GROUNDS", "ADMIN COORDINATOR" = "ADMINISTRATIVE COORDINATOR",
                 "SUPVG MEDICAL SERVICE COORD,CCS" = "SUPERVISING MEDICAL SERVICE COORDINDATOR, CALIFORNIA CHILDREN SERVICES",
                 "WELFR" = "WELFARE", "RECIP" = "RECIPIENT", "VEND" = "VENDOR", "SUPT"="SUPERINTENDENT", "MECHANIC APP" = "MECHANIC APPRENTICE",
                 "PULMONARY PHYSIOLOGY, TECH SUPVR" = "PULMONARY PHYSIOLOGY TECHNICIAN SUPERVISOR", 
                 "PUBLIC DEF" = "PUBLIC DEFENDER", "MNGR" = "MANAGER", "AVRC" = "ANTELOPE VALLEY REHABILITATION CENTER",
                 "REGIONAL PLANNIN" = "REGIONAL PLANNING", "PW" = "PUBLIC WORKS", "HS" = "HEALTH SERVICES",
                 "TRANSP"="TRANSPORTATION", "DCS" = "DEPARTMENT OF CHILDREN SERVICES", "COMPREHEN" = "COMPREHENSIVE",
                 "HCC" = "HEALTH CARE CENTER", "ADMN SVCS" = "ADMINISTRATIVE SERVICES","B & H" = "BEACHES & HARBORS",
                 "PUBL" = "PUBLIC", "PRINC" = "PRINCIPAL", "DEP" = "DEPUTY", "COMLPL" = "COMPLIANCE", 
                 "PGM ADMN" = "PROGRAM ADMINISTRATOR", "EQUIP OPER" = "EQUIPMENT OPERATOR", "PRG ADMN" = "PROGRAM ADMINISTRATOR",
                 "PLT OPER" = "PLANT OPERATOR", "INVR" = "INVESTIGATOR", "RES ANALYS" = "RESEARCH ANALYST", "RES" = "RESEARCH",
                 "ASST." = "ASSISTANT", "EXEC." = "EXECUTIVE", "MGR." = "MANAGER", "CONSERV." = "CONSERVATOR",
                 "BOARD OF SUPVRS." = "BOARD OF SUPERVISORS", "H.S." = "HEALTH SERVICES", "SUPVRS." = "SUPERVISORS", 
                 "CHIEF COUNSEL, DISAB." = "CHIEF COUNSEL, DISABILITY", "ADMIN DEPUTY, CHILD" = "ADMINISTRATIVE DEPUTY, CHILD",
                 "TRNG" = "TRAINING", "INT" = "INTERMEDIATE")

abbrev_pattern <- str_c("\\b", names(abbrev_list), "\\b", collapse = "|")

abbrev2long <- function(abbr) {
    abbrev_list[abbr]
}

# Remove all periods in the titles
current_titles$TitleLong <- str_remove_all(current_titles$TitleLong, "\\.")

current_titles$TitleLong <- str_replace_all(current_titles$TitleLong,
                                      pattern = abbrev_pattern,
                                      replacement = abbrev2long)